### ISSUE TITLE
Improve mnist pipeline example

### ISSUE THREAD

**Issue by Jeffwan** [aws-samples/eks-kubeflow-workshop#33]
https://github.com/aws-samples/eks-kubeflow-workshop/blob/master/notebooks/05_Kubeflow_Pipeline/05_03_Pipeline_mnist.ipynb

1.  Consider to use random names for mnist-ui, mnist-model. Otherwise user has to delete resources to rerun the pipeline. This brings some challenges to  get exact name for inference. There's a tradeoff and we should keep simplification in mind and make changes to improve experiences. 

Reference: commands to delete resources
```
k delete deployment mnist-model  mnist-ui
k delete svc mnist-service  mnist-ui
k delete vs mnist-ui
```

> Note: k is alias of `kubectl -n kubeflow`

2.  Currently, user doesn't have permission to check kubeflow namespace. Check why this doesn't work? 
```
kubectl create --namespace=anonymous rolebinding --clusterrole=kubeflow-view --serviceaccount=anonymous:default-editor anonymous-kubeflow-view 
```

Otherwise, we just give user `cluster-admin` permission which is not recommended but works.

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: anonymous-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: anonymous

```

3. Provides Dockerfile and update python to write event logs, write an artifact to enable tensorboard

4. Use high level KFP Op to construct TFjob instead of ResourceOp

5. Consider to pass S3 MNIST training data to pipeline instead of download dataset in the code. Add instructions to replace S3 export bucket to user's
